Implement simulation mode (#90)
Co-authored-by: jayaprabhakar <jayaprabhakar@gmail.com>

diff --git a/fizz b/fizz
--- a/fizz
+++ b/fizz
@@ -4,12 +4,13 @@ SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 WORKING_DIR="$(pwd)"
 
 usage() {
-  echo "Usage: $0 [-x|--simulation] filename"
+  echo "Usage: $0 [-x|--simulation] [--seed int64Number] filename"
   exit 1
 }
 
 # Initialize variables
 simulation=false
+seed=0
 
 # Parse options
 while [[ "$1" =~ ^- ]]; do
@@ -17,6 +18,15 @@ while [[ "$1" =~ ^- ]]; do
     -x | --simulation )
       simulation=true
       shift
+      ;;
+    --seed )
+      if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
+        seed="$2"
+        shift 2
+      else
+        echo "Error: --seed requires a numeric value." 1>&2
+        usage
+      fi
       ;;
     --internal_profile )
       internal_profile=true
@@ -87,6 +97,10 @@ fi
 if [ "$internal_profile" = true ]; then
   args+=("--internal_profile")
 fi
+if [ "$seed" -ne 0 ]; then
+  args+=("--seed" "$seed")
+fi
+
 args+=("$json_filename")
 
 
