Add a way to override the constants using a preinit hook (#279)
Co-authored-by: jayaprabhakar <jayaprabhakar@gmail.com>

diff --git a/fizz b/fizz
--- a/fizz
+++ b/fizz
@@ -32,7 +32,7 @@ if [[ $# -gt 0 ]]; then
 fi
 
 usage() {
-  echo "Usage: $0 [-x|--simulation] [--test] [--seed int64Number] [--max_runs intNumber] [--exploration_strategy dfs] [--trace tracefile] filename"
+  echo "Usage: $0 [-x|--simulation] [--test] [--seed int64Number] [--max_runs intNumber] [--exploration_strategy dfs] [--trace tracefile] [--preinit-hook hookfile] filename"
   exit 1
 }
 
@@ -43,6 +43,7 @@ max_runs=0
 exploration_strategy=bfs
 test=false
 trace_file=""
+preinit_hook_file=""
 
 # Parse options
 while [[ "$1" =~ ^- ]]; do
@@ -88,6 +89,15 @@ while [[ "$1" =~ ^- ]]; do
         shift 2
       else
         echo "Error: --trace requires a file path." 1>&2
+        usage
+      fi
+      ;;
+    --preinit-hook )
+      if [[ -n "$2" ]]; then
+        preinit_hook_file="$2"
+        shift 2
+      else
+        echo "Error: --preinit-hook requires a file path." 1>&2
         usage
       fi
       ;;
@@ -158,6 +168,9 @@ if [ "$exploration_strategy" != "bfs" ]; then
 fi
 if [ -n "$trace_file" ]; then
   args+=("--trace" "$trace_file")
+fi
+if [ -n "$preinit_hook_file" ]; then
+  args+=("--preinit-hook" "$preinit_hook_file")
 fi
 
 args+=("$json_filename")
