ci: Add build and release (#177)
* ci: add release ci

* ci: add build

* ci: add build

* fix: incorrect VERSION

* fix: add fizz.env

* fix: DISABLE_CLEANUP

* fix: remove auto building in fizz

* docs: update README.md

diff --git a/fizz b/fizz
--- a/fizz
+++ b/fizz
@@ -1,7 +1,16 @@
 #!/bin/bash
 
+# fail on error
+set -e
+
 SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]:-$0}")")"
 WORKING_DIR="$(pwd)"
+SCRIPT_ENV_FILE="$SCRIPT_DIR/fizz.env"
+
+# load envs
+if [[ -f $SCRIPT_ENV_FILE ]]; then
+  source $SCRIPT_ENV_FILE
+fi
 
 usage() {
   echo "Usage: $0 [-x|--simulation] [--seed int64Number] [--max_runs intNumber] [--exploration_strategy dfs] filename"
@@ -77,24 +86,9 @@ fi
 
 input_filename=$1
 
-# Check if the script directory and working directory are the same
-if [ "$SCRIPT_DIR" = "$WORKING_DIR" ]; then
-
-    # Check if parser_bin exists, otherwise run bazel build
-    if ! test -f bazel-bin/parser/parser_bin; then
-      echo "bazel-bin/parser/parser_bin not found. Running 'bazel build parser/parser_bin'!"
-      bazel build parser/parser_bin
-    fi
-    # Check if fizzbee exists, otherwise run bazel build
-    if ! test -f bazel-bin/fizzbee_/fizzbee; then
-        echo "bazel-bin/fizzbee_/fizzbee not found. Running 'bazel build //:fizzbee'!"
-        bazel build //:fizzbee
-    fi
-fi
-
 # Set the paths for the binaries relative to the script directory
-PARSER_BIN="$SCRIPT_DIR/bazel-bin/parser/parser_bin"
-FIZZBEE_BIN="$SCRIPT_DIR/bazel-bin/fizzbee_/fizzbee"
+PARSER_BIN="${PARSER_BIN:-$SCRIPT_DIR/bazel-bin/parser/parser_bin}"
+FIZZBEE_BIN="${FIZZBEE_BIN:-$SCRIPT_DIR/bazel-bin/fizzbee_/fizzbee}"
 
 # Call the first binary and redirect output to a temporary file
 temp_output=$(mktemp)
